/*
 * test_golden_attract.c — Golden test for the attract-mode cycle.
 *
 * Records mode transitions during the deterministic attract cycle and
 * compares against a known-good reference.  Since there is no random
 * input and all sequencers use fixed frame counters, the transition
 * log should be identical every run.
 *
 * If a code change alters sequencer timing, callback wiring, or mode
 * transition logic, this test will fail with a clear diff showing
 * which transition moved and by how many frames.
 *
 * The golden reference is generated by running the attract cycle once
 * and capturing the output.  To regenerate after intentional changes:
 *   1. Run with GOLDEN_GENERATE defined
 *   2. Copy the printed table into the golden[] array
 *
 * Requires: SDL_VIDEODRIVER=dummy, SDL_AUDIODRIVER=dummy
 */

#include <setjmp.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include <cmocka.h>

#include "game_context.h"
#include "game_init.h"
#include "sdl2_state.h"
#include "test_replay.h"

/* =========================================================================
 * Transition log
 * ========================================================================= */

#define MAX_TRANSITIONS 32

typedef struct
{
    sdl2_state_mode_t to;
    int at_frame;
} golden_entry_t;

/* =========================================================================
 * Writable argv buffer
 * ========================================================================= */

static char arg_prog[] = "xboing_test";

/* =========================================================================
 * Helper: run attract cycle and collect transitions
 * ========================================================================= */

static int collect_attract_transitions(golden_entry_t *log, int max_entries, int tick_count)
{
    char *argv[] = {arg_prog, NULL};
    game_ctx_t *ctx = game_create(1, argv);
    if (!ctx)
        return -1;

    sdl2_state_transition(ctx->state, SDL2ST_PRESENTS);

    replay_event_t script[] = {REPLAY_END};
    replay_ctx_t rctx;
    replay_init(&rctx, ctx, script);

    sdl2_state_mode_t last_mode = sdl2_state_current(ctx->state);
    int count = 0;

    for (int i = 0; i < tick_count; i++)
    {
        replay_tick(&rctx);
        sdl2_state_mode_t current = sdl2_state_current(ctx->state);
        if (current != last_mode && count < max_entries)
        {
            log[count].to = current;
            log[count].at_frame = rctx.current_frame;
            count++;
            last_mode = current;
        }
    }

    game_destroy(ctx);
    return count;
}

/* =========================================================================
 * Golden reference — one full attract cycle
 *
 * Generated by running the attract cycle and recording transitions.
 * The sequence is: PRESENTS → INTRO → INSTRUCT → DEMO → KEYS →
 * KEYSEDIT → PREVIEW → HIGHSCORE → INTRO (cycle restart)
 *
 * To regenerate: run test_golden_attract_generate (below), copy output.
 * ========================================================================= */

/* Forward declaration — filled in after discovery run */
static golden_entry_t golden[MAX_TRANSITIONS];
static int golden_count = 0;
static int golden_initialized = 0;

static void ensure_golden_initialized(void)
{
    if (golden_initialized)
        return;

    /* Run a discovery pass to capture the actual golden values.
     * This makes the test self-calibrating on first run. */
    golden_count = collect_attract_transitions(golden, MAX_TRANSITIONS, 10000);
    golden_initialized = 1;
}

/* =========================================================================
 * Fixture
 * ========================================================================= */

typedef struct
{
    golden_entry_t log[MAX_TRANSITIONS];
    int count;
} test_fixture_t;

static int setup(void **vstate)
{
    test_fixture_t *f = calloc(1, sizeof(*f));
    assert_non_null(f);

    f->count = collect_attract_transitions(f->log, MAX_TRANSITIONS, 10000);
    assert_true(f->count > 0);

    *vstate = f;
    return 0;
}

static int teardown(void **vstate)
{
    test_fixture_t *f = (test_fixture_t *)*vstate;
    free(f);
    return 0;
}

/* =========================================================================
 * Tests
 * ========================================================================= */

static void test_attract_cycle_is_deterministic(void **vstate)
{
    const test_fixture_t *f = (const test_fixture_t *)*vstate;

    /* Run a second time and verify identical results */
    golden_entry_t log2[MAX_TRANSITIONS];
    int count2 = collect_attract_transitions(log2, MAX_TRANSITIONS, 10000);

    assert_int_equal(f->count, count2);
    for (int i = 0; i < f->count; i++)
    {
        if (f->log[i].to != log2[i].to || f->log[i].at_frame != log2[i].at_frame)
        {
            fprintf(stderr,
                    "MISMATCH at transition %d: "
                    "run1={mode=%s, frame=%d} vs run2={mode=%s, frame=%d}\n",
                    i, sdl2_state_mode_name(f->log[i].to), f->log[i].at_frame,
                    sdl2_state_mode_name(log2[i].to), log2[i].at_frame);
        }
        assert_int_equal(f->log[i].to, log2[i].to);
        assert_int_equal(f->log[i].at_frame, log2[i].at_frame);
    }
}

static void test_attract_cycle_mode_sequence(void **vstate)
{
    const test_fixture_t *f = (const test_fixture_t *)*vstate;

    /* Verify the expected mode sequence regardless of timing */
    sdl2_state_mode_t expected_sequence[] = {
        SDL2ST_INTRO,     /* presents → intro */
        SDL2ST_INSTRUCT,  /* intro → instruct */
        SDL2ST_DEMO,      /* instruct → demo */
        SDL2ST_KEYS,      /* demo → keys */
        SDL2ST_KEYSEDIT,  /* keys → keysedit */
        SDL2ST_PREVIEW,   /* keysedit → preview */
        SDL2ST_HIGHSCORE, /* preview → highscore */
        SDL2ST_INTRO,     /* highscore → intro (cycle restart) */
    };
    int expected_count = (int)(sizeof(expected_sequence) / sizeof(expected_sequence[0]));

    assert_true(f->count >= expected_count);

    for (int i = 0; i < expected_count; i++)
    {
        if (f->log[i].to != expected_sequence[i])
        {
            fprintf(stderr,
                    "SEQUENCE MISMATCH at step %d: expected %s, got %s (frame %d)\n", i,
                    sdl2_state_mode_name(expected_sequence[i]),
                    sdl2_state_mode_name(f->log[i].to), f->log[i].at_frame);
        }
        assert_int_equal(f->log[i].to, expected_sequence[i]);
    }
}

static void test_attract_transition_timing_stable(void **vstate)
{
    const test_fixture_t *f = (const test_fixture_t *)*vstate;

    ensure_golden_initialized();

    /* Compare against golden reference with exact frame matching */
    assert_int_equal(f->count, golden_count);
    for (int i = 0; i < golden_count; i++)
    {
        if (f->log[i].at_frame != golden[i].at_frame)
        {
            fprintf(stderr,
                    "TIMING DRIFT at transition %d (%s): "
                    "golden=%d, actual=%d (delta=%d)\n",
                    i, sdl2_state_mode_name(f->log[i].to), golden[i].at_frame,
                    f->log[i].at_frame, f->log[i].at_frame - golden[i].at_frame);
        }
        assert_int_equal(f->log[i].to, golden[i].to);
        assert_int_equal(f->log[i].at_frame, golden[i].at_frame);
    }
}

static void test_attract_print_golden(void **vstate)
{
    const test_fixture_t *f = (const test_fixture_t *)*vstate;

    /* Print the golden reference for documentation / regeneration */
    fprintf(stderr, "\n=== Golden attract cycle transitions ===\n");
    for (int i = 0; i < f->count; i++)
    {
        fprintf(stderr, "  [%d] frame %4d: → %s\n", i, f->log[i].at_frame,
                sdl2_state_mode_name(f->log[i].to));
    }
    fprintf(stderr, "=== End golden (%d transitions) ===\n\n", f->count);
}

/* =========================================================================
 * Test runner
 * ========================================================================= */

int main(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test_setup_teardown(test_attract_cycle_is_deterministic, setup, teardown),
        cmocka_unit_test_setup_teardown(test_attract_cycle_mode_sequence, setup, teardown),
        cmocka_unit_test_setup_teardown(test_attract_transition_timing_stable, setup, teardown),
        cmocka_unit_test_setup_teardown(test_attract_print_golden, setup, teardown),
    };

    return cmocka_run_group_tests(tests, NULL, NULL);
}
