#!/usr/bin/env bash
# Generate docs/adr_table.tex from the ADR headers in docs/DESIGN.md.
#
# DRY: docs/DESIGN.md is the single source of truth for ADRs. The LaTeX
# reports \input the generated table instead of hand-transcribing 74 rows.
# Re-run after adding an ADR, then recompile the affected PDFs.
#
# Usage: scripts/gen_adr_table.sh   (writes docs/adr_table.tex)
#
# The single-quoted sed/printf strings below emit literal LaTeX backslashes on
# purpose; SC2016 (no expansion wanted) and SC1003 (backslash before quote) are
# both false positives here.
# shellcheck disable=SC2016,SC1003
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
src="${repo_root}/docs/DESIGN.md"
out="${repo_root}/docs/adr_table.tex"

[ -f "$src" ] || { echo "error: $src not found" >&2; exit 1; }

latex_escape() {
    # Escape the LaTeX specials that appear in ADR titles.
    sed -e 's/\\/\\textbackslash{}/g' \
        -e 's/&/\\\&/g' \
        -e 's/%/\\%/g' \
        -e 's/#/\\#/g' \
        -e 's/_/\\_/g' \
        -e 's/\$/\\$/g' \
        -e 's/{/\\{/g' \
        -e 's/}/\\}/g' \
        -e 's/\^/\\textasciicircum{}/g' \
        -e 's/~/\\textasciitilde{}/g' \
        -e 's/`\([^`]*\)`/\\texttt{\1}/g'
}

{
    printf '%s\n' '% GENERATED by scripts/gen_adr_table.sh from docs/DESIGN.md — do not edit by hand.'
    printf '%s\n' '\begin{longtable}{lp{13cm}}'
    printf '%s\n' '\caption{Architectural Decision Records (generated from \filename{docs/DESIGN.md})} \label{tab:adrs} \\'
    printf '%s\n' '\toprule'
    printf '%s\n' '\textbf{ADR} & \textbf{Title} \\'
    printf '%s\n' '\midrule'
    printf '%s\n' '\endfirsthead'
    printf '%s\n' '\toprule'
    printf '%s\n' '\textbf{ADR} & \textbf{Title} \\'
    printf '%s\n' '\midrule'
    printf '%s\n' '\endhead'
    printf '%s\n' '\bottomrule'
    printf '%s\n' '\endfoot'
    grep -oE '^#+ ADR-[0-9]+:.*' "$src" | sed -E 's/^#+ ADR-([0-9]+): *(.*)$/\1\t\2/' | \
    while IFS=$'\t' read -r num title; do
        esc_title="$(printf '%s' "$title" | latex_escape)"
        printf '%s & %s \\\\\n' "$num" "$esc_title"
    done
    printf '%s\n' '\end{longtable}'
} > "$out"

echo "wrote $out ($(grep -cE '^[0-9]+ &' "$out") ADR rows)"
