#!/usr/bin/env bash
# Generate docs/metrics.tex (LaTeX \newcommand macros) from docs/metrics.json.
#
# DRY: docs/metrics.json is the single source of truth for project figures.
# The LaTeX reports \input docs/metrics.tex and reference \MetricXxx macros
# instead of hard-typing numbers. Re-run after updating metrics.json, then
# recompile the PDFs — the figures propagate mechanically.
#
# Usage: scripts/gen_metrics_tex.sh   (writes docs/metrics.tex)
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
src="${repo_root}/docs/metrics.json"
out="${repo_root}/docs/metrics.tex"

command -v jq >/dev/null || { echo "error: jq required" >&2; exit 1; }
[ -f "$src" ] || { echo "error: $src not found" >&2; exit 1; }

# Format an integer with a LaTeX thin-space thousands separator (1{,}337).
group() { printf '%s' "$1" | awk '{n=$0; out=""; while(length(n)>3){out="{,}" substr(n,length(n)-2) out; n=substr(n,1,length(n)-3)} print n out}'; }

j() { jq -r "$1" "$src"; }

{
    echo "% GENERATED by scripts/gen_metrics_tex.sh from docs/metrics.json — do not edit by hand."
    printf '\\newcommand{\\MetricVersion}{%s}\n'        "$(j '.version.value')"
    printf '\\newcommand{\\MetricFirstCommit}{%s}\n'    "$(j '.work_span.first_commit')"
    printf '\\newcommand{\\MetricLastCommit}{%s}\n'     "$(j '.work_span.last_commit')"
    printf '\\newcommand{\\MetricMonths}{%s}\n'         "$(j '.work_span.approx_months')"
    printf '\\newcommand{\\MetricMergedPRs}{%s}\n'      "$(group "$(j '.git.merged_prs.value')")"
    printf '\\newcommand{\\MetricCommits}{%s}\n'        "$(group "$(j '.git.commits_on_master.value')")"
    printf '\\newcommand{\\MetricADRs}{%s}\n'           "$(group "$(j '.adrs.total.value')")"
    printf '\\newcommand{\\MetricSrcLines}{%s}\n'       "$(group "$(j '.source_lines.modern_src.cloc_code')")"
    printf '\\newcommand{\\MetricSrcFiles}{%s}\n'       "$(j '.source_lines.modern_src.files')"
    printf '\\newcommand{\\MetricHdrLines}{%s}\n'       "$(group "$(j '.source_lines.modern_headers.cloc_code')")"
    printf '\\newcommand{\\MetricHdrFiles}{%s}\n'       "$(j '.source_lines.modern_headers.files')"
    printf '\\newcommand{\\MetricTestLines}{%s}\n'      "$(group "$(j '.source_lines.tests.cloc_code')")"
    printf '\\newcommand{\\MetricTestFiles}{%s}\n'      "$(j '.source_lines.tests.files')"
    printf '\\newcommand{\\MetricLegacyLines}{%s}\n'    "$(group "$(j '.source_lines.legacy_src.cloc_code')")"
    printf '\\newcommand{\\MetricLegacyFiles}{%s}\n'    "$(j '.source_lines.legacy_src.files_c')"
    printf '\\newcommand{\\MetricCmockaCases}{%s}\n'    "$(group "$(j '.tests.cmocka_cases.value')")"
    printf '\\newcommand{\\MetricCtestSuites}{%s}\n'    "$(j '.tests.ctest_suites.value')"
    printf '\\newcommand{\\MetricBeadsClosed}{%s}\n'    "$(group "$(j '.beads.closed')")"
    printf '\\newcommand{\\MetricBeadsTotal}{%s}\n'     "$(group "$(j '.beads.total')")"
    printf '\\newcommand{\\MetricLevels}{%s}\n'         "$(j '.content.levels.value')"
    printf '\\newcommand{\\MetricClosedMissions}{%s}\n' "$(group "$(j '.ethos.closed_missions.value')")"
} > "$out"

echo "wrote $out"
